version: "3.9"

services:
  server:
    container_name: server
    build:
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - pgdb
    volumes:
      - .:/home/app
    ports:
      - 3000:3000

  pgdb:
    build: ./docker/postgres
    container_name: psqldatabase
    tty: true
    restart: always
    volumes:
      - ./docker/dbdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=dbpaint

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    tty: true
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@user.com
      - PGADMIN_DEFAULT_PASSWORD=123456
    ports:
      - 9002:80
